**CREATE ONE DIMENSIONAL TENSOR**

In [1]:
import numpy as np

In [2]:
tensor_id = np.array([1.3, 1, 4.0, 23.99])

In [3]:
print(tensor_id)

[ 1.3   1.    4.   23.99]


In [4]:
print(tensor_id[0])

1.3


In [5]:
print(tensor_id[2])

4.0


**CREATE TWO DIMENSIONAL TENSOR**

In [6]:
import numpy as np

In [7]:
tensor_2d = np.array([(1, 2, 3, 4), (4, 5, 6, 7), (8, 9, 10, 11), (12, 13, 14, 15)])

In [8]:
print(tensor_2d)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [9]:
tensor_2d[3] [2]

14

**TENSOR HANDLING AND MANIPULATION**

In [10]:
import tensorflow as tf
import numpy as np

2023-11-18 01:20:54.232361: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-18 01:20:54.235855: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-18 01:20:54.272295: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-18 01:20:54.272336: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-18 01:20:54.273863: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to

In [11]:
matrix1 = np.array([(2, 2, 2), (2, 2, 2), (2, 2, 2)], dtype = 'int32')
matrix2 = np.array([(1, 1, 1), (1, 1, 1), (1, 1, 1)], dtype = 'int32')

In [12]:
print(matrix1)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [13]:
print(matrix2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)
matrix_product = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1, matrix2)
matrix_sub = tf.subtract(matrix1, matrix2)
matrix_div = tf.divide(matrix1, matrix2)
matrix_3 = np.array([(2, 7, 2), (1, 4, 2), (9, 0, 2)], dtype = 'float32')
print(matrix_3)
print(matrix_product)
print(matrix_sum)
print(matrix_sub)
print(matrix_div)

[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]
tf.Tensor(
[[6 6 6]
 [6 6 6]
 [6 6 6]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[3 3 3]
 [3 3 3]
 [3 3 3]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]], shape=(3, 3), dtype=float64)


In [15]:
#importing the library
import tensorflow as tf

In [16]:
#initializing the input tensor
a = tf.constant([7, 8, 13, 11], dtype = tf.float64)
b = tf.constant([2, 13, 14, 5], dtype = tf.float64)

In [17]:
#printing the input tensor
print('a:', a)
print('b:', b)

a: tf.Tensor([ 7.  8. 13. 11.], shape=(4,), dtype=float64)
b: tf.Tensor([ 2. 13. 14.  5.], shape=(4,), dtype=float64)


In [18]:
res = tf.math.less(x = a, y = b)

In [19]:
print('Result:', res)

Result: tf.Tensor([False  True  True False], shape=(4,), dtype=bool)
